### PR TITLE
Add custom source of distribute 0.6.49 for downloading

### PR DESCRIPTION
**Pull request by wpoely86**
The PR for which this is need can be found at
https://github.com/hpcugent/easybuild-framework/pull/1490

This is the source of distribute 0.6.49 with the file
`_markerlib/markers.py` replaced by the 0.6 version of
markerlib which can be found at
https://pypi.python.org/pypi/markerlib/0.6.0

### CODE REVIEW

**Comment by wpoely86** [comment]
@boegel please merge so I can retest the PR

**Comment by boegel** [comment]
@wpoely86: hmm, can we rename the tarball to indicate it's patched version, while still allowing it to be picked up?

maybe something like `files/distribute-0.6.49-1.tar.gz` (or, if possible, something more descriptive than the extra `-1`)?

**Comment by wpoely86** [comment]
@boegel that's more patching in the bootstrap scripts of distribute...

**Comment by boegel** [comment]
@wpoely86: the tarball name is hardcoded? we're already patching it, so shouldn't be that hard?

**Comment by wpoely86** [comment]
It's possible
but there might be unexpected fallout...

**Comment by wpoely86** [comment]
@boegel done, please merge

**Pull request merged**
