### PR TITLE
mention need to escape % when configuring log file format via configuration file

### PR DESCRIPTION
**Pull request by boegel**
@fgeorgatos, @wpoely86: please review?

### CODE REVIEW

**Comment by wpoely86** [comment]
looks fine but why does it need to be so?

**Comment by boegel** [comment]
Here's why:

```
```

**Comment by boegel** [comment]
Here's why:

```
Traceback (most recent call last):
  File "/home/example/.local/lib/python2.6/site-packages/easybuild_framework-2.0.0dev-py2.6.egg/easybuild/main.py", line 336, in <module>
    main()
  File "/home/example/.local/lib/python2.6/site-packages/easybuild_framework-2.0.0dev-py2.6.egg/easybuild/main.py", line 158, in main
    eb_go = eboptions.parse_options(args=args)
  File "/home/example/.local/lib/python2.6/site-packages/easybuild_framework-2.0.0dev-py2.6.egg/easybuild/tools/options.py", line 668, in parse_options
    eb_go = EasyBuildOptions(usage=usage, description=description, prog='eb', envvar_prefix='EASYBUILD', go_args=args)
  File "/home/example/.local/lib/python2.6/site-packages/easybuild_framework-2.0.0dev-py2.6.egg/easybuild/tools/options.py", line 98, in __init__
    super(EasyBuildOptions, self).__init__(*args, **kwargs)
  File "/home/example/.local/lib/python2.6/site-packages/easybuild_framework-2.0.0dev-py2.6.egg/vsc/utils/generaloption.py", line 763, in __init__
    self.parseconfigfiles()
  File "/home/example/.local/lib/python2.6/site-packages/easybuild_framework-2.0.0dev-py2.6.egg/vsc/utils/generaloption.py", line 1173, in parseconfigfiles
    for opt, val in self.configfile_parser.items(section):
  File "/usr/lib64/python2.6/ConfigParser.py", line 578, in items
    for option in options]
  File "/usr/lib64/python2.6/ConfigParser.py", line 614, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib64/python2.6/ConfigParser.py", line 646, in _interpolate_some
    option, section, rest, var)
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
        section: [config]
        option : logfile-format
        key    : time
        rawval : .log'
```

**Comment by boegel** [comment]
@wpoely86: updated the note with the actual error message being thrown, for easy searching

**Comment by boegel** [comment]
merging via #71, thanks for the review @wpoely86!

**Pull request closed without merging**
