### PR TITLE
only use raw URL for bootstrap script

### PR DESCRIPTION
**Pull request by boegel**
@verdurin: please review?

### CODE REVIEW

**Comment by verdurin** [comment]
@boegel - bootstrapping works on a `Fedora 23` vagrant box with this URL, but the old problem of EB not detecting `Lmod` on Fedora is back...

**Comment by verdurin** [comment]
```
[vagrant@localhost ~]$ ml EasyBuild
[vagrant@localhost ~]$ eb -S M4
== temporary log file in case of crash /tmp/eb-otF1kR/easybuild-ZimdA4.log
ERROR: EnvironmentModulesC modules tool can not be used, 'modulecmd' command is not available.
```

**Comment by boegel** [comment]
@verdurin is `$LMOD_CMD` defined? If not, you need to define `$EASYBUILD_MODULES_TOOL` to `Lmod`; the bootstrap script doesn't pick up the `module` function yet

**Comment by verdurin** [comment]
@boegel - couldn't remember what the latest workaround for this was. Setting `$EASYBUILD_MODULES_TOOL` to `Lmod` does indeed fix it.

**Comment by verdurin** [comment]
Trying now on a `CentOS 7.2` box.

**Comment by verdurin** [comment]
On that box, I see this error:

```
+++ STAGE 2: installing EasyBuild in /home/vagrant/.local/easybuild with EasyBuild from stage 1...


Traceback (most recent call last):
  File "bootstrap_eb.py", line 787, in <module>
    main()
  File "bootstrap_eb.py", line 590, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 508, in stage2
    easybuild_main()
  File "/tmp/tmpgVlSSU/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/main.py", line 198, in main
    eb_go = eboptions.parse_options(args=args)
  File "/tmp/tmpgVlSSU/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.8.1-py2.7.egg/easybuild/tools/options.py", line 1016, in parse_options
    raise EasyBuildError("Failed to parse configuration options: %s" % err)
easybuild.tools.build_log.EasyBuildError: "Failed to parse configuration options: 'Found 1 environment variable(s) that are prefixed with EASYBUILD but do not match valid option(s): EASYBUILD_PREFIX_HOME'"
```

**Comment by boegel** [comment]
@verdurin well, you have misconfigured EB there, there's no `--prefix-home`, so `EASYBUILD_PREFIX_HOME` is not a valid config option

**Comment by boegel** [comment]
but, we're getting off track here, this PR was meant to just change the download URL to the raw one, which seems to be OK, so I'll merge this in

**Comment by verdurin** [comment]
@boegel - yes, well - I like to test all the parameter space, as you know...

Works fine on `CentOS 7.2` as well, as long as the module tool variable is set to `Lmod` too.

**Pull request merged**
